### ISSUE TITLE
when start server 

### ISSUE THREAD

**Issue by omarlachhab** [sonos-web/sonos-web#53] opened 2020-08-26 10:03 UTC
![Capture](https://user-images.githubusercontent.com/30928791/91290655-ca604a80-e78b-11ea-82ba-c7740baacb22.PNG)

**Comment by jamestalmage** [comment] 2020-09-21 21:49
I am also having this issue.

**Comment by jat255** [comment] 2020-09-24 20:07
:+1:  seeing this too using Node v14.12.0 and npm v6.14.8 on a Debian 10 server

**Comment by jat255** [comment] 2020-09-24 20:08
This appears to be a duplicate of #41

**Closed as completed** 2022-08-21 05:52 UTC
