### ISSUE TITLE
Sonos System not detected

### ISSUE THREAD

**Issue by ebnels** [sonos-web/sonos-web#12] opened 2019-04-19 21:54 UTC
Been having this issue since successfully installing sonos-web on ubuntu 18.04. When opening web browser, I get the message "Searching for Sonos System" but none of the components are detected. I have an old ZP100 and a Play5 connected to my network and I can successfully ping each device. However, I am getting the following error in my sonos-web.log: "UnhandledPromiseRejectionWarning: Error: Not A Sonos Device". Here is my completed sonos-web.log file:

{ clientId: 'd8058916213248f4b40bc0cc6d69ae46',
  clientSecret: '2836db0cbfcc44e58de8c67265730a35',
  redirectUri: 'http://localhost:5050/spotify' }
Server listening on port 5050
(node:5953) UnhandledPromiseRejectionWarning: Error: Not A Sonos Device
    at new MusicLibrary (/home/eric/.sonos-web/src/sonos/MusicLibrary.js:14:30)
    at _discover.then (/home/eric/.sonos-web/src/sonos/SonosNetwork.js:49:29)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:5953) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5953) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any help would be appreciated

**Comment by Villarrealized** [comment] 2019-05-04 15:26
Hi there. Sorry it has taken me a while to respond. Have been quite busy.

The following function is where the issue and initialization takes place:

```javascript
_init() {
    this.initializing = true;
    this._discover(this.timeout).then((devices) => {
      if (!this.musicLibrary) {
        // ***This line below is where the Not A Sonos Device error is being thrown***
        this.musicLibrary = new MusicLibrary(devices[0]);
      }
      // Build the zone groups
      this._parseZoneGroups().then(() => {
        this.socketio.emit(SonosDeviceDiscoveryComplete, this.zoneGroups);
        this.initializing = false;
      }).catch((error) => {
        this.initializing = false;
        console.log(error);
        if (error.message === NoDevicesFound) {
          this.socketio.emit(NoSonosDevicesFound);
        } else {
          this.socketio.emit(
            UnknownErrorWhileRetrievingDevices,
            JSON.stringify(error, Object.getOwnPropertyNames(error)),
          );
        }
      });
      // Now that we have the devices, listen for events on them
      this._listen();
    });
  }

```

My guess is that the 5 second timeout for discovering the Sonos devices on your network is not enough. My suggestion would be to increase it in the file `server/src/sonos/SonosNetwork.js`

```javascript
class SonosNetwork {
  // Increase the timeout to 10000 (10 seconds)
  constructor(socketio, timeout = 5000) {
    this.socketio = socketio;
    this.devices = [];
    this.zoneGroups = [];
    this.timeout = timeout;
    this.initializing = true;
    this.listener = Listener;
    this.musicLibrary = null;

    this._init();
    this.socketio.on('connection', () => {
      if (this.initializing) {
        this.socketio.emit(DiscoveringSonosDevices);
      } else if (this.zoneGroups.length === 0) {
        this._init();
      } else {
        this.socketio.emit(SonosDeviceDiscoveryComplete, this.zoneGroups);
      }
    });
  }
```

**Comment by ebnels** [comment] 2019-05-06 12:53
Thanks for getting back to me. I’ll give it a try and let you know.

Thanks.

**Comment by ebnels** [comment] 2019-05-06 13:32
Thanks again for the advice. However, I increased the timeout to 10 seconds and its still throwing the same error.

**Comment by Villarrealized** [comment] 2019-05-18 19:39
Have you made any further progress on this? This project uses [node-sonos](https://github.com/bencevans/node-sonos/tree/master/lib) to discover and interact with Sonos on your network. So, if you can, I would suggest trying to see if you can get a simple discover example working directly from that project.  If you can get it to work, then the issue is with Sonos Web and we can try to debug that further.

**Comment by ebnels** [comment] 2019-05-21 00:58
Sorry. Haven't had time to try and sleuth it out further. I'll see whether I can figure it out through node-sonos and let you know. I really want to get this to work. It will be very useful. Thanks for your work.

**Comment by Villarrealized** [comment] 2019-11-11 03:17
Closing this issue for now until further need.

**Closed as completed by Villarrealized** 2019-11-11 03:17 UTC
